# for no exception
print("Starting line")

try:
    a=10/5
except:
    print("Some exception raise")
else:
    print("No exception raised,everything working prefectly")
finally:
    print("This is final block")
print("Outside try block")

# for sone exception
print("Starting line")

try:
    a=10/0
except:
    print("Some exception raise")
else:
    print("No exception raised,everything working prefectly")
finally:
    print("This is final block")
print("Outside try block")
